[package]
name = "gpu_fan_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_lib = {version = "0.1.0", path = "my_lib"}
